name: Development - Deploy static website

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1
  S3_BUCKET: "vishwa-bucketiiiii"

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Copy files
      run: |
          aws s3 cp . s3://${{ env.S3_BUCKET }}/ --recursive --exclude "*" --include "*.html" --include "images/*"
          echo "Deployment done"
